package View.Items;
import javax.swing.*;
public class Buttons {
    public static final ImageIcon def_accept =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\blue_button_accept.png" );
    public static final ImageIcon focus_accept =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\green_button_accept.png" );
    public static final ImageIcon press_accept =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\red_button_accept.png" );
    public static final ImageIcon def_login =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\blue_button_login.png" );
    public static final ImageIcon focus_login =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\green_button_login.png" );
    public static final ImageIcon press_login =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\red_button_login.png" );
    public static final ImageIcon def_recovery =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\blue_button_recovery.png" );
    public static final ImageIcon focus_recovery =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\green_button_recovery.png" );
    public static final ImageIcon press_recovery =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\red_button_recovery.png" );
    public static final ImageIcon def_back =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\blue_button_back.png" );
    public static final ImageIcon focus_back =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\green_button_back.png" );
    public static final ImageIcon press_back =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\red_button_back.png" );
    public static final ImageIcon def_quit =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\blue_button_quit.png" );
    public static final ImageIcon focus_quit =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\green_button_quit.png" );
    public static final ImageIcon press_quit =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\red_button_quit.png" );
    public static final ImageIcon def_register =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\blue_button_register.png" );
    public static final ImageIcon focus_register =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\green_button_register.png" );
    public static final ImageIcon press_register =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\red_button_register.png" );
    public static final ImageIcon def_sg =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\blue_menu_button_sg.png" );
    public static final ImageIcon focus_sg =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\green_menu_button_sg.png" );
    public static final ImageIcon press_sg =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\red_menu_button_sg.png" );
    public static final ImageIcon def_bp =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\pur_menu_button_bp.png" );
    public static final ImageIcon focus_bp =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\green_menu_button_bp.png" );
    public static final ImageIcon press_bp =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\red_menu_button_bp.png" );
    public static final ImageIcon def_gc =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\blue_menu_button_gc.png" );
    public static final ImageIcon focus_gc =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\green_menu_button_gc.png" );
    public static final ImageIcon press_gc =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\red_menu_button_gc.png" );
    public static final ImageIcon def_cn =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\pur_menu_button_cn.png" );
    public static final ImageIcon focus_cn =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\green_menu_button_cn.png" );
    public static final ImageIcon press_cn =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\red_menu_button_cn.png" );
    public static final ImageIcon def_out =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\blue_menu_button_out.png" );
    public static final ImageIcon focus_out =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\green_menu_button_out.png" );
    public static final ImageIcon press_out =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\red_menu_button_out.png" );
    public static final ImageIcon def_menu_quit =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\pur_menu_button_quit.png" );
    public static final ImageIcon focus_menu_quit =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\green_menu_button_quit.png" );
    public static final ImageIcon press_menu_quit =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\red_menu_button_quit.png" );
    public static final ImageIcon def_menu_back =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\blue_menu_button_back.png" );
    public static final ImageIcon focus_menu_back =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\green_menu_button_back.png" );
    public static final ImageIcon press_menu_back =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\red_menu_button_back.png" );
    public static final ImageIcon def_bj =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\blue_menu_button_bj.png" );
    public static final ImageIcon focus_bj =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\green_menu_button_bj.png" );
    public static final ImageIcon press_bj =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\red_menu_button_bj.png" );
    public static final ImageIcon def_sm =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\pur_menu_button_sm.png" );
    public static final ImageIcon focus_sm =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\green_menu_button_sm.png" );
    public static final ImageIcon press_sm =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\red_menu_button_sm.png" );
    public static final ImageIcon def_cf =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\pur_menu_button_cf.png" );
    public static final ImageIcon focus_cf =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\green_menu_button_cf.png" );
    public static final ImageIcon press_cf =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\red_menu_button_cf.png" );
    public static final ImageIcon def_rl =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\pur_menu_button_rl.png" );
    public static final ImageIcon focus_rl =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\green_menu_button_rl.png" );
    public static final ImageIcon press_rl =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\red_menu_button_rl.png" );
    public static final ImageIcon def_jp =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\blue_menu_button_jp.png" );
    public static final ImageIcon focus_jp =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\green_menu_button_jp.png" );
    public static final ImageIcon press_jp =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\red_menu_button_jp.png" );
    public static final ImageIcon def_lobby_cg =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\blue_lobby_button_cg.png" );
    public static final ImageIcon focus_lobby_cg =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\green_lobby_button_cg.png" );
    public static final ImageIcon press_lobby_cg =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\red_lobby_button_cg.png" );
    public static final ImageIcon def_lobby_upd =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\blue_lobby_button_upd.png" );
    public static final ImageIcon focus_lobby_upd =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\green_lobby_button_upd.png" );
    public static final ImageIcon press_lobby_upd =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\red_lobby_button_upd.png" );
    public static final ImageIcon def_lobby_cn =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\pur_lobby_button_cn.png" );
    public static final ImageIcon focus_lobby_cn =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\green_lobby_button_cn.png" );
    public static final ImageIcon press_lobby_cn =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\red_lobby_button_cn.png" );
    public static final ImageIcon def_lobby_back =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\pur_lobby_button_back.png" );
    public static final ImageIcon focus_lobby_back =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\green_lobby_button_back.png" );
    public static final ImageIcon press_lobby_back =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\red_lobby_button_back.png" );
    public static final ImageIcon def_lobby_create =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\pur_lobby_button_create.png" );
    public static final ImageIcon focus_lobby_create =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\green_lobby_button_create.png" );
    public static final ImageIcon press_lobby_create =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\red_lobby_button_create.png" );
    public static final ImageIcon def_ready =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\blue_lobby_button_ready.png" );
    public static final ImageIcon focus_ready =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\green_lobby_button_ready.png" );
    public static final ImageIcon press_ready =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\red_lobby_button_ready.png" );
    public static final ImageIcon def_hit =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\blue_bj_button_hit.png" );
    public static final ImageIcon focus_hit =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\green_bj_button_hit.png" );
    public static final ImageIcon press_hit =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\red_bj_button_hit.png" );
    public static final ImageIcon def_stay =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\blue_bj_button_stay.png" );
    public static final ImageIcon focus_stay =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\green_bj_button_stay.png" );
    public static final ImageIcon press_stay =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\red_bj_button_stay.png" );
    public static final ImageIcon def_restart =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\blue_lobby_button_restart.png" );
    public static final ImageIcon focus_restart =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\green_lobby_button_restart.png" );
    public static final ImageIcon press_restart =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\red_lobby_button_restart.png" );
    public static final ImageIcon def_back_room =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\blue_lobby_button_backr.png" );
    public static final ImageIcon focus_back_room =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\green_lobby_button_backr.png" );
    public static final ImageIcon press_back_room =
            new ImageIcon( "C:\\Users\\Admin\\Desktop\\static final BABOON\\NOTcasino\\Resources\\Buttons\\red_lobby_button_backr.png" );
    public Buttons(){}
}
